### ISSUE TITLE
vernacular_name to return in output

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/infinitylists#14]
Suggestion from @shawnlaffan :)

**Comment by tmesaglio** [comment]
I'm fairly neutral on this, but to play devil's advocate:

1 most Australian plant species don't have a common name, so that value will be blank anyway
2 the window is pretty crowded already, and this will add another column which I personally don't see as being of high (or any) use to a lot of users of this app (most the botanists)

**Comment by shawnlaffan** [comment]
It's best not to assume most users will be botanists, especially if it takes off amongst citizen scientists and the general public.  

Even if not plotted by default, a mechanism to get at the common name remains useful.  Possibly it could be a popup on mouse hover or long press (for touch screen devices).  Or have an expander option to show extra details where available, e.g. common name on a new line in the relevant table cell.

**Comment by tmesaglio** [comment]
done
