### ISSUE TITLE
questions from Dorothy Luther

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/infinitylists#72]
1. In the table, only the date is presented, but in the CSV that column also includes the time; should be consistent between the two (either remove from CSV, or add to table)
2. The 'Observed by' column in the table gets renamed to 'Recorded by' in the CSV, should be consistent
3. The 'Establishment means' column in the table gets renamed to 'native_anywhere_in_aus' in the CSV, should be consistent
4. The 'Repository' column in the table gets renamed to 'Voucher location' in the CSV, should be consistent

**Comment by fontikar** [comment]
Nice observations Dorothy! 
- I think the time is just how R contains date information, and we need the time for the time zone stuff to work. This doesn't seem like such a big deal to me 

So interesting that there are so many inconsistencies, is it because we do a lot of 'data wrangling' in the server script? if so, it would be great to modularise that bit.

**Comment by wcornwell** [comment]
Yeah we rename when calculate the most recent obs for a species. This is partially unavoidable, because some of the columns are syntheses of two different columns (e.g. the links).  There might be some rationalization that could be done, but this will work for now.
